from selenium.webdriver.common.by import By
class Locators:
    BUTTON_FORGOT_PASSWORD = (By.XPATH, "//a[@href = '/forgot-password']")
    EMAIL_FIELD = (By.XPATH, '//input[@class= "text input__textfield text_type_main-default"]')
    BUTTON_RECOVER = (By.XPATH, "//button['button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa']")
    PASSWORD_FIELD = (By.XPATH, "//input[contains(@class,'text_type_main-default') and @type = 'password' ]")
    SHOW_PASSWORD_BUTTON = (By.XPATH, "//div[@class = 'input__icon input__icon-action']")
    PASSWORD_TEXT = (By.XPATH, "//input[contains(@class, 'input__textfield') and contains(@class, 'text_type_main-default') and @type='text']")
    BUTTON_PERSONAL_ACCOUNT = (By.XPATH, "//a[contains(@class, 'AppHeader_header__link__3D_hX') and @href = '/account']")
    BUTTON_ORDER_HISTORY = (By.XPATH, "//a[@class = 'Account_link__2ETsJ text text_type_main-medium text_color_inactive']")
    BUTTON_EXIT = (By.XPATH, "//button[@class = 'Account_button__14Yp3 text text_type_main-medium text_color_inactive']")
    BUTTON_ENTER = (By.XPATH, "//button[@class = 'button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa']")
    BUTTON_CONSTRUCTOR = (By.XPATH, "//a[contains(@class, 'AppHeader_header__link__3D_hX') and @href = '/']")
    BUTTON_ORDER_FEED = (By.XPATH, "//a[contains(@class, 'AppHeader_header__link__3D_hX') and @href = '/feed']")
    FIRST_INGREDIENT = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient__1TVf6') and @href='/ingredient/61c0c5a71d1f82001bdaaa6d']")
    BUTTON_CLOSE = (By.XPATH, "//button[@class = 'Modal_modal__close_modified__3V5XS Modal_modal__close__TnseK']")
    TEXT_ON_MAIN_PAGE = (By.XPATH, "//h1[@class = 'text text_type_main-large mb-5 mt-10']")
    TEXT_INGREDIENT = (By.XPATH, "//h2[@class = 'Modal_modal__title_modified__3Hjkd Modal_modal__title__2L34m text text_type_main-large pl-10']")
    SECOND_INGREDIENT = (By.XPATH, "//a[@href = '/ingredient/61c0c5a71d1f82001bdaaa72']")
    CONSTRUCTOR = (By.XPATH, "//li[@class = 'BurgerConstructor_basket__listItem__aWMu1 mr-4']")
    INGREDIENTS_COUNTER = (By.XPATH, "//p[@class = 'counter_counter__num__3nue1']")
    BUTTON_PLACE_ORDER = (By.XPATH, "//button[@class = 'button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg']")
    TEXT_ORDER_ID = (By.XPATH, "//p[@class = 'undefined text text_type_main-medium mb-15']")
    ORDER_FIELD = (By.XPATH, "//a[@class = 'OrderHistory_link__1iNby']")
    TEXT_INGREDIENT_BURGER_ORDER = (By.XPATH, "//p[@class = 'text text_type_main-medium mb-8']")
    NUMBER_ORDER = (By.XPATH,"//p[@class = 'text text_type_digits-default']")
    COMPLETED_IN_ALL_TIME = (By.XPATH, "//p[@class = 'OrderFeed_number__2MbrQ text text_type_digits-large']")
    COMPLETED_TODAY = (By.XPATH, "//p[contains(text(), 'Выполнено за сегодня:')]/following-sibling::p")
    ORDER_IN_PROGRESS = (By.XPATH,"//ul[contains(@class, 'OrderFeed_orderListReady__1YFem')]/li")
    ORDER_NUMBER_FROM_MAIN_PAGE = (By.XPATH, "//h2[@class = 'Modal_modal__title_shadow__3ikwq Modal_modal__title__2L34m text text_type_digits-large mb-8']")
    LOGIN_PAGE = (By.XPATH, "//div[@class = 'Auth_login__3hAey']")
    ACCOUNT_PAGE = (By.XPATH, "//a[@class = 'Account_link__2ETsJ text text_type_main-medium text_color_inactive Account_link_active__2opc9']")
    RECOVER_PASSWORD_PAGE = (By.XPATH, "//div[@class = 'input pr-6 pl-6 input_type_text input_size_default']")
    SHADOW_FORM_ORDER = (By.XPATH,"//div[@class = 'Modal_modal_opened__3ISw4 Modal_modal__P3_V5']")


